### ISSUE TITLE
Are you still interrested to use Terraform (or Ansible)?

### ISSUE THREAD

**Issue by cdlhub** [OasisLMF/Deployment#14]
I would like to investigate deployment automation. I would rather use Ansible because I already know it. However, I am open to use Terraform if it is more coherent with your tools and infrastructure.
What do you think?

**Comment by sambles** [comment]
Both sounds interesting, however keep in mind that we're aiming to remove the SQL server component for the next release.

**Comment by cdlhub** [comment]
I opened a branch to test Ansible deployment:
https://github.com/cdlhub/Deployment/tree/mst_ansible
