### ISSUE TITLE
piwind_worker container reboots every 10 sec

### ISSUE THREAD

**Issue by imprompt** [OasisLMF/Deployment#16]
Just updated to latest Deployment but model executtion worker reboots every 10 sec.
Is this normal (I don't remember it from previously)?
This is using latest vanilla PiWind for testing:
```
cd Deployment
git pull
cd compose
./oasis_service up
```
![docker](https://user-images.githubusercontent.com/26572903/53878395-0dfd4c80-400c-11e9-8e32-1cc1d244f8fe.png)

**Comment by mpinkerton-oasis** [comment]
@sambles can you take a look please
